### ISSUE TITLE
Tool buttons generating separate tabs

### ISSUE THREAD

**Issue by nomadscientist** [usegalaxy-au/galaxy-labs-engine#14]
The tool buttons in the single-cell domain are no longer opening a Galaxy in a Galaxy (yay!) but now instead are opening a separate tab for running the tool.
They need to open the tool within the same tab in the Galaxy.

Example to recreate error:
![Screenshot 2024-11-28 at 15 15 03](https://github.com/user-attachments/assets/e7f99e8a-1422-485c-8c46-c8c21a9b4350)

**Comment by neoformit** [comment]
Sorry Wendi, this is technically not really possible because an iframe (i.e. the lab page embedded in Galaxy) cannot change the location of the parent page. That's why it has to open in a new tab :cry:

**Comment by nomadscientist** [comment]
Dang - how does the GTN tutorial mode do it?

**Comment by neoformit** [comment]
That's a good question - @hexylena do you know how an iframe can change the parent frame (Galaxy) location?

**Comment by hexylena** [comment]
I mean there's _top /_parent as a target wouldn't that work? but the GTn does some special things namely having galaxy proxy us in order to be on the same origin, and then we can access Galaxy's javascript to load tools or navigate or do whatever. we're looking at replacing that with posting messages between the frames but haven't implemented that yet due to some browser specific oddities.

**Comment by neoformit** [comment]
Holy hell, in all this time I have never come across `target="_top/_parent"`. So glad I pinged you! 😆 Yes I had wondered about the potential of message posting between frames, I thought that might have been your solution. @nomadscientist I'll look into a fix using this tomorrow.

**Comment by hexylena** [comment]
hope it works out! 

if you do return to post message in the future, https://github.com/galaxyproject/training-material/pull/5344 was my attempt but we ended up reverting because chrome sent far too many messages and I wasn't handling them carefully enough. you have to handle them very, very carefully 🥲 it was unpleasant, I should've tested more browsers and OSes

I think it's definitely the better option long term, since it'll let galaxy host tutorial mode without the proxy  (which is unattractive for many reasons.) But I'm not sure when we'll get around to it, and it'll still need code on the galaxy side to handle message passing.

**Comment by neoformit** [comment]
Resolved by #18
External links now open in new tab, and current galaxy links (e.g. singlecell.usegalaxy.eu/tool) open in the top frame.
Amazeballs, thanks @hexylena this has bothered me for years :laughing:
